# Generated by Django 5.1.4 on 2025-01-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgencyName', models.CharField(blank=True, max_length=30, null=True)),
                ('Location', models.CharField(blank=True, max_length=30, null=True)),
                ('ContactPerson', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('PhoneNo', models.BigIntegerField(blank=True, null=True)),
                ('Services', models.CharField(blank=True, max_length=150, null=True)),
                ('Destinations', models.CharField(blank=True, max_length=150, null=True)),
                ('OperatingHours', models.IntegerField(blank=True, null=True)),
                ('EstablishedYear', models.IntegerField(blank=True, null=True)),
                ('Ratings', models.CharField(blank=True, max_length=300, null=True)),
                ('Status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('ContactNumber', models.BigIntegerField(blank=True, null=True)),
                ('EmailID', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RouteNo', models.CharField(blank=True, max_length=20, null=True)),
                ('PlaneNo', models.CharField(blank=True, max_length=20, null=True)),
                ('DepartureDate', models.CharField(blank=True, max_length=10, null=True)),
                ('DepartureTime', models.CharField(blank=True, max_length=10, null=True)),
                ('DepartureLocation', models.CharField(blank=True, max_length=50, null=True)),
                ('ArrivalTime', models.CharField(blank=True, max_length=10, null=True)),
                ('ArrivalLocation', models.CharField(blank=True, max_length=50, null=True)),
                ('TicketPrice', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(blank=True, max_length=50, null=True)),
                ('HotelType', models.CharField(blank=True, max_length=30, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('Country', models.CharField(blank=True, max_length=30, null=True)),
                ('NumberOfRooms', models.IntegerField(blank=True, null=True)),
                ('Facilities', models.CharField(blank=True, max_length=200, null=True)),
                ('PetPolicy', models.CharField(blank=True, max_length=20, null=True)),
                ('ContactNo', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Website', models.CharField(blank=True, max_length=100, null=True)),
                ('BasePrice', models.FloatField(blank=True, null=True)),
                ('RoomType', models.CharField(blank=True, max_length=30, null=True)),
                ('AdditionalFee', models.FloatField(blank=True, null=True)),
                ('HotelStatus', models.CharField(blank=True, max_length=20, null=True)),
                ('CheckInTime', models.CharField(blank=True, max_length=20, null=True)),
                ('CheckOutTime', models.CharField(blank=True, max_length=20, null=True)),
                ('Description', models.CharField(blank=True, max_length=250, null=True)),
                ('Images', models.FileField(blank=True, null=True, upload_to='rooms/')),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('usertype', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(blank=True, max_length=50, null=True)),
                ('Details', models.CharField(blank=True, max_length=200, null=True)),
                ('Duration', models.CharField(blank=True, max_length=50, null=True)),
                ('Facility', models.CharField(blank=True, max_length=200, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placename', models.CharField(blank=True, max_length=30, null=True)),
                ('Spotname', models.CharField(blank=True, max_length=30, null=True)),
                ('Category', models.CharField(blank=True, max_length=30, null=True)),
                ('Description', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.FileField(blank=True, max_length=30, null=True, upload_to='Places/')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('bookingDetails', models.CharField(blank=True, max_length=30, null=True)),
                ('ContactNumber', models.BigIntegerField(blank=True, null=True)),
                ('Totalguests', models.IntegerField(blank=True, null=True)),
                ('BookingStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('PaymentStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytravelapp.customertable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, max_length=15, null=True)),
                ('Feedback', models.CharField(blank=True, max_length=300, null=True)),
                ('CustomerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytravelapp.customertable')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GalleryImage', models.FileField(blank=True, max_length=30, null=True, upload_to='')),
                ('AgencyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytravelapp.agencytable')),
            ],
        ),
        migrations.CreateModel(
            name='RatingsAndReviewsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, max_length=20, null=True)),
                ('Ratings', models.IntegerField(blank=True, null=True)),
                ('Review', models.CharField(blank=True, max_length=150, null=True)),
                ('CustomerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytravelapp.customertable')),
            ],
        ),
    ]
