# Generated by Django 5.1.4 on 2025-01-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytravelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtable',
            old_name='bookingDetails',
            new_name='BookingDetails',
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='Date',
            field=models.DateField(auto_now_add=True, default='2025-01-11'),
            preserve_default=False,
        ),
    ]
