# Generated by Django 5.1.4 on 2025-02-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytravelapp', '0002_rename_bookingdetails_bookingtable_bookingdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencytable',
            name='Ratings',
        ),
        migrations.AddField(
            model_name='ratingsandreviewstable',
            name='AgencyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytravelapp.agencytable'),
        ),
    ]
